---
- name: Install Docker on Amazon Linux 2
  hosts: all
  become: true

  tasks:
    - name: Install Docker package
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
